language: cpp

compiler:
  - gcc
#  - clang

before_install:
  - sudo apt-get remove cmake --purge
  - sudo apt-get install expect
  - chmod +x installcmake.sh
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.sh
  - sudo ./installcmake.sh
  - ls /usr/cmake-3.2.1-Linux-x86_64
  - sudo ln -s /usr/cmake-3.2.1-Linux-x86_64/bin/cmake /usr/bin/cmake

before_script:
  - ./configure
  - ./configure portable

script:
  - cd build
  - make
