language: cpp

compiler:
  - gcc
#  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.7
  - pwd
  - sudo apt-get remove cmake --purge
  - sudo apt-get install expect
  - chmod +x installcmake.sh
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.sh
  - sudo ./installcmake.sh
  - ls /usr/cmake-3.2.1-Linux-x86_64
  - sudo ln -s /usr/cmake-3.2.1-Linux-x86_64/bin/cmake /usr/bin/cmake
  - git clone https://github.com/gunmetalbackupgooglecode/googletest.git gtest
  - git clone https://github.com/gunmetalbackupgooglecode/googlemock.git googlemock
  - cd googlemock
  - cmake . -DBUILD_SHARED_LIBS=true
  - make
  - cd ..
  - cd gtest
  - cmake . -DBUILD_SHARED_LIBS=true
  - make
  - cd ..

before_script:
  - ./configure
  - echo "export GMOCK_HOME=/home/travis/build/gunmetalbackupgooglecode/pdbparser/googlemock" >> ".localconfig/portable"
  - echo "export GTEST_HOME=/home/travis/build/gunmetalbackupgooglecode/pdbparser/gtest" >> ".localconfig/portable"
  - ./configure portable

script:
  - cd build
  - make
  - make test
