language: cpp

compiler:
  - gcc
#  - clang

before_install:
    # from wisk
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get -qq install boost1.55 gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

  
  - pwd
  - sudo apt-get remove cmake --purge
  - sudo apt-get install expect
  - chmod +x installcmake.sh
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.sh
  - sudo ./installcmake.sh
  - ls /usr/cmake-3.2.1-Linux-x86_64
  - sudo ln -s /usr/cmake-3.2.1-Linux-x86_64/bin/cmake /usr/bin/cmake
  - git clone https://github.com/gunmetalbackupgooglecode/googletest.git gtest
  - git clone https://github.com/gunmetalbackupgooglecode/googlemock.git googlemock
  - cd googlemock
  - cmake . -DBUILD_SHARED_LIBS=true
  - make
  - cd ..
  - cd gtest
  - cmake . -DBUILD_SHARED_LIBS=true
  - make
  - cd ..

before_script:
  - ./configure
  - echo "export GMOCK_HOME=/home/travis/build/gunmetalbackupgooglecode/pdbparser/googlemock" >> ".localconfig/portable"
  - echo "export GTEST_HOME=/home/travis/build/gunmetalbackupgooglecode/pdbparser/gtest" >> ".localconfig/portable"
  - ./configure portable

script:
  - cd build
  - make
  - make test
