language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get remove cmake --purge
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.sh
  - sudo sh cmake-3.2.0-rc2-Linux-x86_64.sh --prefix=/opt/cmake
  - PATH=~/opt/cmake/bin/:$PATH

before_script:
  - ./configure
  - ./configure portable

script:
  - cd build
  - make
